import type { Metadata } from "next";
import "./globals.css";
import Script from 'next/script'
import Header from '../components/Common/Header'
import Footer from '../components/Common/Footer'



export const metadata: Metadata = {
  title: "Walmart Vriddhi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Header/>
        {children}
        <Footer/>
      </body>
        {/* <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" /> */}
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js" defer ></Script>
      
    </html>
  );
}
